version: "3.7"

services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
      TZ: "Europe/Zurich"

  lavalink:
    image: fredboat/lavalink:master
    ports:
      - 2333:2333
    volumes:
      - ./resources/lavalink/application.yml:/opt/Lavalink/application.yml
      - ./resources/lavalink/logs:/opt/Lavalink/logs
    # If it comes to serving a large amount of guilds, increasing the allocated memory is a must.
    # Change -Xmx to your prefered size. E.g: -Xmx2G for 2GB memory allocated.
    entrypoint: java -Xmx2G -jar Lavalink.jar

  bot:
    build: .
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./logs:/bot/logs
      - "/etc/localtime:/etc/localtime:ro"
